//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Track_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusLocation
    {
        public int BL_Id { get; set; }
        public Nullable<int> B_Id { get; set; }
        public Nullable<int> L_Id { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Location Location { get; set; }
    }
}
