//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Track_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> P_Id { get; set; }
        public Nullable<int> B_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Class { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
